spring.application.name=SalesManagement

# spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SalesManagement;encrypt=true;trustServerCertificate=true
spring.datasource.url=jdbc:sqlserver://sqlserver:1433;databaseName=sales;encrypt=true;trustServerCertificate=true
# spring.datasource.url=jdbc:sqlserver://sqlserver:1433;databaseName=sales;encrypt=true;trustServerCertificate=true
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:Trungkien132@}

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret-key=${JWT_SECRET_KEY:aGVsbG93b3JsZHRoaXNpc2FzdXBlcnN1cGVydmVyeWxvbmdhbmRzdHJvbmdzZWNyZXRrZXlhbmRkb250dGVsbG1ldGhhdHRoaXNpc25vdGxvbmdlbm91Z2hvcnRvb3Nob3J0}
jwt.expiration=900000
jwt.refresh-expiration=604800000

# Redis configuration
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
# Cache TTL (in seconds) - 1 hour by default
app.cache.ttl=3600